version: '3.7'

services:
  db: 
    image: postgres:14-alpine
    container_name: goreads
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 20
    environment: 
      POSTGRES_DB: goreads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks: 
      - goreads_net

  api: 
    build: ./backend
    container_name: goreads_api
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - 3333:3333
    environment: 
      DATABASE_URL: postgresql://postgres:1234@db:5432/goreads?schema=public
      JWT_SECRET: jwt_secret
    networks: 
      - goreads_net

  web: 
    build: ./frontend
    container_name: goreads_web
    depends_on:
      - api
      - db
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/goreads
    networks: 
      - goreads_net

networks:
  goreads_net: 
    driver: bridge
